### ISSUE TITLE
unreleased packages should not list as errors

### ISSUE THREAD

**Issue by ssbarnea** [eight04/pip-outdated#3]
It is missleading to use red color to present packages that were not released yet. Maybe you could use yellow/orange to display them as their are clearly not out of version specifiers.

![screenshot](https://sbarnea.com/ss/Screen-Shot-2019-09-15-17-05-27.png)

**Comment by eight04** [comment]
We should filter out prerelease from the version list around here:
https://github.com/eight04/pip-outdated/blob/160c5b3eebc192603bd9eeaf693763684c9dd90d/pip_outdated/check_outdated.py#L42
Something like:
https://github.com/eight04/vpip/blob/fd3a11c525a5b917ac2332458615db80d6ca0642/vpip/pypi.py#L40
