### ISSUE TITLE
Find extras_require in setup.cfg

### ISSUE THREAD

**Issue by ssbarnea** [eight04/pip-outdated#4]
Extras are not loaded at all. As we are using test requirements via extras this also means that we cannot use pip-outdated to report test requirements.

As an example, please https://github.com/ansible/molecule/blob/master/setup.cfg#L100-L142 which is a project having lots of extras and which is also using the declarative format to declare them.

Extra are optional dependencies which can be installed using `pip install foo[sqlite,mysql]`.

Considering that pip-outdated is used a dependency debugging / investigation tool, I do expect it to load all extras and to report their status. Probably it would be useful to list them separated from the default dependencies, or at least to have another column which would document which extra did require it.

**Comment by eight04** [comment]
Can you elaborate? What is your input and what do you expect?

**Comment by eight04** [comment]
Have to modify `parse_cfg`:
https://github.com/eight04/pip-outdated/blob/160c5b3eebc192603bd9eeaf693763684c9dd90d/pip_outdated/find_require.py#L51

Maybe we should use a config parser.

**Comment by ssbarnea** [comment]
@eight04 I am sure you do want to use the same parser as pip or setuptools, you do want to re implement the same logic yourself.
