### ISSUE TITLE
proposal: use exit code to inform about errors

### ISSUE THREAD

**Issue by ssbarnea** [eight04/pip-outdated#5]
In order to be able to use the tool in CI to detect possible problems we need to make it return an non zero error code when problems are detected.

I am not sure if you want this to be triggered with a special argument or default, or which type of problems should be considered errors.

For example an outdated but still in range dependency should not trigger an execution error.

Think about the exit code from `pip check`, which returns 0 when no conflicts are found but returns non-zero when these are found. A similar kind of behavior would be desirable.

**Comment by eight04** [comment]
An *installed package* has 3 states:

1. All good.
2. Incompatible. The version doesn't match the specifier.
3. Outdated. The version matches the specifier, but it is not the latest version which can match the specifier.

A *dependency specifier* has 2 states:

1. All good. The specifier includes the latest release.
2. Outdated. The specifier doesn't include the latest release.

We should consider which triggers an error. (and maybe to make it configurable through CLI options)

**Comment by eight04** [comment]
In v0.3.0, pip-outdated returns 1 if the table is displayed.
