### ISSUE TITLE
Unbounded requirements shown in red

### ISSUE THREAD

**Issue by jonnyarnold** [eight04/pip-outdated#8]
I've got a project where my development tools are not a specific version:

```
# requirements-dev.txt
black
isort
pip-outdated
```

When I run this file through pip-outdated, I get the following output:

```
Red = unavailable/outdated/out of version specifier
Green = updatable
+-------+-----------+--------+--------+
| Name  | Installed | Wanted | Latest |
+-------+-----------+--------+--------+
| black | 19.3b0    | None   | None   |  <-- (red)
+-------+-----------+--------+--------+
```

I have a feeling that this is due to the version not being specified - but if that was the case, wouldn't `isort` and `pip-outdated` also be in this list?

I've had a quick look through the code, but couldn't find anything obviously wrong.

Let me know if I can be of any further help!

**Comment by eight04** [comment]
pip-outdated ignores all beta versions, so it can't find a version that is compatible with the installed `black` and is marked as "outdated":
https://github.com/eight04/pip-outdated/blob/f6002341755f19adad8a4dcea007a377e5b7acad/pip_outdated/check_outdated.py#L34

For other packages, I believe that you have installed the latest version. When no version is specified, pip-outdated uses the latest version as "wanted".

**Comment by jonnyarnold** [comment]
Great stuff - thanks for the quick response!
